name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: eslint
      #   uses: hallee/eslint-action@1.0.3
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     source-root: frontend
      - name: black
        uses: lgeiger/black-action@master
        with:
          args: "api --check"
